_target_: models.ffa.FFA
name: FFA

net:
  _target_: models.nets.ffa_net.FFANet
  name: "dinov2_vitb14"
  variant: "Crop-Feat"

img_transform:
  _target_: transforms.TransformFFA
  img_size: 336
  margin: 10
  square: true