_target_: models.wdisi.WhereDidISeeIt
name: WDISI

net:
  _target_: models.nets.wdisi_net.WDISINet
  name: "vit_b_16"
  pretrained: true
  num_heads: 8
  img_size: 224

criterion:
  _target_: losses.triplet.TripletLoss
  name: "Triplet"
  margin: 1.0

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 20
  eta_min: 0.001

img_transform:
  _target_: transforms.TransformReOBJ
  img_size: 224
  margin: 10
  square: false