# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - dataset: coda
  - model: clover
  - paths: default
  - hydra: default
  - experiment: null

data:
  num_workers: 4

project_name: "Object Identification (CLOVER)"
task_name: "eval"
name: "default"

ckpt_path: null
seed: null
wandb: True