# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - dataset: coda
  - model: clover
  - paths: default
  - experiment: null

task_name: "eval"
name: "default"

data:
  num_workers: 4

ckpt_path: null

seed: null