# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - model: clover
  - dataset: coda
  - paths: default
  - hydra: default
  - experiment: null

data:
  num_workers: 4

train:
  max_epochs: 100
  early_stopping: 10

project: "CLOVER (Object Re-Identification)"
task: "train"
name: ${dataset.name}_${model.name}
tags: []

ckpt_path: null
seed: 42
wandb: True